### ISSUE TITLE
Fix CRLF line endings

### ISSUE THREAD

**Issue by stweil** [altoxml/schema#78]
v4/alto-4-2.xsd and v4/alto-4-3.xsd got the wrong line endings.

Is it still possible to replace CRLF by LF for those two files?

**Comment by cipriandinu** [comment]
Hi, I think is not really "wrong" as I know CRLF is used on Windows based systems, LF in Unix world and CR on Mac world. Probably I am the guilty one since I am using Windows based machine, but I don't know exactly when and how this change appears since I haven't done anything explicit. I will propose this topic on the next meeting and we should come to a decision what should be the prefered format and then we should see how to ensure this is not changed accidentally.

**Comment by stweil** [comment]
Mac uses LF like Unix / Linux. And the convention for Git repositories is using LF for all kinds of text files. Then Windows users can choose whether their Git should convert that to CRLF.

**Comment by cipriandinu** [comment]
There is any fast way to make this change directly in Git (for 4.2, 4.3 and the current "in progress" version 4.4)? Then since I am only editing directly in browser the files, the issue should not appear. I am not a real expert in using Git, some help would be great :)

**Comment by cipriandinu** [comment]
Great, thank you! Probably we should do it again for 4.4 since the branch for adding is based on older 4.3 (containing CRLF).

**Comment by cipriandinu** [comment]
@stweil I would propose to close this topic, since the issue was solved with your help. Also 4.4 proposal looks to be updated. Do you agree?
